default:
	@echo 'Targets:'
	@echo '  test'

test:
	# ./noaa-client.py --latitude 39.44 --longitude -84.3 --startDateTime 2020-05-16T00:00:00 --endDateTime 2020-05-20T23:00:00
	./noaa-client.py --latitude 39.44 --longitude -84.3
